### ISSUE TITLE
出现不明错误

### ISSUE THREAD

**Issue by xiaoyang212** [BecauseY/Library-Management-System#1]
Traceback (most recent call last):
  File "d:\桌面\github\Library-Management-System\main_widget.py", line 34, in login_button_function
    self.user = func.signin(user_mes)
  File "d:\桌面\github\Library-Management-System\func.py", line 42, in signin
    if conn:
UnboundLocalError: local variable 'conn' referenced before assignment
![微信图片_20221124194712](https://user-images.githubusercontent.com/83319298/203777221-650c5a3a-bdbd-41e1-b2e3-1ba4be46264f.png)

**Comment by BecauseY** [comment]
> 

这是func.py的第12行连接数据库的时候没连接成功应该，你自己debug试试，这不是什么大问题

**Comment by BecauseY** [comment]
这是func.py的第12行连接数据库的时候没连接成功应该，你自己debug试试，这不是什么大问题

**Comment by BecauseY** [comment]
这是func.py的第15行连接数据库的时候没连接成功应该，你自己debug试试，这不是什么大问题

**Comment by xiaoyang212** [comment]
已经解决了，多谢大佬的源码



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月27日 18:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [BecauseY/Library-Management-System] 出现不明错误 (Issue #1) |

这是func.py的第12行连接数据库的时候没连接成功应该，你自己debug试试，这不是什么大问题

**Comment by Wpf0** [comment]
哥们你怎么解决的
