### ISSUE TITLE
管理员登录失败

### ISSUE THREAD

**Issue by SHIHAO2233** [BecauseY/Library-Management-System#2]
学生注册后可以成功登录，但是管理员总是登录失败，而且我好像记得我第一次登录管理员的时候可以登录，之后再重新调试都没办法登录了呜呜呜
![image](https://user-images.githubusercontent.com/76611529/215350288-951e6ca6-705f-45a3-87f8-7059e7d1f042.png)

**Comment by BecauseY** [comment]
这个应该是读取数据库失败了吧，你试试debug一下func.py的signin函数，一行行试试看看哪行出错了

**Comment by BecauseY** [comment]
> 学生注册后可以成功登录，但是管理员总是登录失败，而且我好像记得我第一次登录管理员的时候可以登录，之后再重新调试都没办法登录了呜呜呜 ![image](https://user-images.githubusercontent.com/76611529/215350288-951e6ca6-705f-45a3-87f8-7059e7d1f042.png)

这个应该是读取数据库失败了吧，你试试debug一下func.py的signin函数，一行行试试看看哪行出错了
