### ISSUE TITLE
登录异常的问题大概是func.py里的登录逻辑有点点小问题

### ISSUE THREAD

**Issue by Rouphy** [BecauseY/Library-Management-System#3]
```
def encrypt(val):
    # import hashlib
    h = sha256()  # 用了hashlib.sha256()
    password = val
    h.update(bytes(password, encoding='UTF-8'))
    result = h.hexdigest()
    # 注释下面一行即可加密
    # result = val
    return result
```
一开始只是测试了一下加密函数encrypy()的逻辑然后发现如果去掉加密就能够正常登录学生账号和管理员账号，数据库里存的是未加密的密码明文；
然后重新加密之后发现，数据库除了管理员账号的密码外，学生账号的密码都是经过加密的密文，但是登录操作sign_in()方法里面压根就没有引用解密或者加密的函数？这点就很令人费解了
我一开始以为大佬的思路是在登录的时候把用户输入加密一遍拿去跟数据库里的密文比较，虽然这种方法的可行性尚且不明（）
### 直接说结论就是：去掉加密之后可以正常使用
正在摸索其他的加密方式来代替sha256带来的不可逆影响

**Comment by BecauseY** [comment]
应该是的，加密是最后加的小功能，可能有点小问题，去掉就行
